config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :jobs do
    resources :registers
  end
  resources :users, only: :show
  match 'save', to: 'saves#save', via: :post
  match 'undo', to: 'saves#undo', via: :delete
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :registers
  has_many :saves, dependent: :destroy
  
  validates :name, presence: true
  validates :title, presence: true
  validates :city, presence: true
  validates :description, presence: true

  def self.search(query)
    where("lower(city) LIKE ? OR lower(title) LIKE ? OR majors LIKE ?", "%#{query.downcase}%", "%#{query.downcase}%", "%#{query.downcase}%")
  end

  def self.order_by_date
    order(:created_at)
  end

  def posted
    created_at.strftime("%m/%d/%Y")
  end

  def self.order_by_city
    order(:city)
  end

  def self.order_by_major
    order(:major)
  end

end

app/models/register.rb
class Register < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/models/safe.rb
class Safe < ApplicationRecord
  belongs_to :job
  belongs_to :user

  validates :user_id, uniqueness: { scope: :job_id }


end

app/models/user.rb
class User < ApplicationRecord
  has_many :jobs
  has_many :registers
  has_many :saves, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def save_job!(job)
    self.saves.create!(job_id: job.id)
  end

  def undo_save!(job)
    save = self.saves.find_by_job_id(job.id)
    save.destroy!
  end

  def saved_job?(job)
    if self.saves.find_by_job_id(job.id)
      true
    else
      false
    end
  end

  def my_saved_jobs
      saves.map(&:job)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?
  def logged_in?
     current_user.present?
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
     if params[:search]
       jobs = Job.search(params[:search])
     elsif params[:sort]
       jobs = sort_jobs
     else
       jobs = Job.all
     end
     @jobs = jobs.paginate(:page => params[:page], :per_page => 2)
  end

  def sort_jobs
    jobs = if params[:sort] == "date"
      Job.order_by_date
    elsif params[:sort] == "city"
      Job.order_by_city
    else
      Job.all
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = current_user.jobs.create(job_params)
    if @job.valid?
      redirect_to jobs_path
    else
      render :new, status: :uprocessable_entity
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])

    if @job.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @job = Job.find(params[:id])
    if @job.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end

    @job.update_attributes(job_params)
    if @job.valid?
      redirect_to jobs_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @job = Job.find(params[:id])
    if @job.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end

    @job.destroy
    redirect_to jobs_path
  end
  private

  def job_params
    params.require(:job).permit(:name, :address, :city, :state, :title, :description, :responsibilities, :requirements, :skills, :majors)
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :authenticate_user!
  def index
    @registers = Register.all
  end

  def show
    @register = Register.find(params[:id])
  end

  def new
    @job = Job.find(params[:job_id])
    @register = Register.new
  end

  def create
    @job = Job.find(params[:job_id])
    @job.registers.create(register_params.merge(user: current_user))
    redirect_to job_path(@job)
  end

  def edit
    @job = Job.find(param[:id])
    @register = @job.registers.find(params[:id])
  end

  def update
    @job = Job.find(params[:job_id])
    @job.registers.update_attributes(register_params)
    redirect_to user_path(current_user)
  end

  def destroy
   @job = Job.find(params[:job_id])
   @register = @job.registers.find(params[:id])
   @register.destroy
   redirect_to user_path(current_user), :notice => "Lesson Deleted"
  end

  private

  def register_params
    params.require(:register).permit(:full_name, :phone_number, :email, :address, :city, :state, :zip, :month,
                                      :highschool, :college, :location, :years, :major, :company_name, :job_title, :description, :goals)
  end
end

app/controllers/saves_controller.rb
class SavesController < ApplicationController
  respond_to :js

  def save
    @user = current_user
    @job = Job.find(params[:job_id])
    @user.save_job!(@job)
  end

  def undo
    @user = current_user
    @save = @user.saves.find_by_job_id(params[:job_id])
    @job = Job.find(params[:job_id])
    @save.destroy!
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/saves_helper.rb
module SavesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Internship</h1>
  <%= simple_form_for @job do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :responsibilities %>
    <%= f.input :requirements %>
    <%= f.input :skills %>
    <%= f.input :majors %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/jobs/index.html.erb

<br />
<div id="search_wrapper" class="form-inline my-2 my-lg-0 col-6 offset-3">
  <%= form_tag(jobs_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], id:"search_field", class:"form-control mr-sm-2", placeholder: "Search for internships by title, major, or city" %>
  <%= button_tag(type: "submit", id:"search_button", class:"btn btn-outline-success my-2 my-sm-0") do %>
      <i class="fa fa-search"></i>
    <% end %>
  <% end %>
</div>
<br />
<div class="booyah-box col-10 offset-1">
  <div class="col-10 offset-1">
    <div class="row">
      <div class="col-6">
        <h1><%= @jobs.count %> Internships Found</h1>
      </div>
      <div id="sort" class="col-6">
        <h5> Sort By: <%= link_to 'Date', jobs_path(:sort => "date") %> |
          <%= link_to 'City', jobs_path(:sort => "city") %> |
          <%= link_to 'Major', jobs_path(:sort => "major") %>
      </div>
    </div>
  </div>
  <div class="jobresults">
  <% if @jobs.present? %>
    <% @jobs.each do |job| %>
      <div class="booyah-box col-10 offset-1" id="jobpost">
        <h1><%=link_to job.title, job_path(job) %></h1>
        <h4><%= job.name %></h4>
        <i><%= job.city %>, <%= job.state %></i><br /><br />
        <p><%= job.description[0..300] %>...</p><br />
        <p>posted: <%= job.posted %></p><br />

      <% if logged_in? %>
        <%= div_for job do %>
          <%= render partial: "saves/button", locals: { job: job} %>
        <% end %>
      <% end %>
      </div>
    <% end %>
  <% else %>
    <p> There are no jobs with that search criteria </p>
  <% end %>
</div>
</div>

<br />
<div class="col-2 offset-5">
  <%= will_paginate %>
</div>

app/views/jobs/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Job Details</h1>
  <%= simple_form_for @job do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :responsibilities %>
  <%= f.input :requirements %>
  <%= f.input :skills %>
  <%= f.input :majors %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/jobs/show.html.erb
<div class="booyah-box col-10 offset-1">
  <h1><%= @job.name %></h1>
  <i><%= @job.address %> <%= @job.city %>,<%= @job.state %></i><hr>
  <br/><br/>
  <h1><%= @job.title %></h1><hr>
  <h5>DESCRIPTION</h5><hr>
  <p><%= @job.description %></p>
  <h5>RESPONSIBILITIES</h5><hr>
  <P><%= @job.responsibilities %></p>
  <h5>REQUIREMENTS</h5><hr>
  <p><%= @job.requirements %></p>
  <h5>SKILLS</h5><hr>
  <p><%= @job.skills %></p>
  <h5>MAJORS</h5><hr>
  <p><%= @job.majors %></p>
  <div class="float-right">
    <% if current_user && current_user == @job.user %>
      <%= link_to 'Edit', edit_job_path(@job), class: 'btn btn-primary' %>
      <%= link_to 'Destroy', job_path(@job), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
      <%= link_to 'APPLY!', new_job_register_path(@job), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<h4 class="col-10 offset-1"><%= @job.registers.count %> Applicants</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div id="flex-content-container">
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <%= link_to 'JOBS', root_path, class: 'navbar-brand' %>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to 'Students', jobs_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Organizations', new_job_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to new_job_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              New Internship
            <% end %>
          </li>
        </ul>
        <!-- <ul class="navbar-nav float-md-right">
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
        </ul>

        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search by keyword, major, or city">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->

        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

      <%= yield %>
    </div>

    <div id="footer">
      <div class="container">
        <b>FOR</b>
        <br />
        <%= link_to 'Students', jobs_path %><br />
        <%= link_to 'Organizations', new_job_path %>
      </div>
    </div>
  </body>
</html>

app/views/registers/new.html.erb
<br />
<h1 class="col-10 offset-1">Apply to this job</h1>
<div class="booyah-box col-10 offset-1">
  <%= simple_form_for @register, url: job_registers_path(@job) do |f| %>
    <%= f.input :full_name %>
    <%= f.input :phone_number %>
    <%= f.input :email %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    Month avaiable to start:
    <%= f.input :month %>
    <%= f.input :highschool %>
    <%= f.input :college %>
    <%= f.input :location %>
    <%= f.input :years %>
    <%= f.input :major %>
    <%= f.input :company_name %>
    <%= f.input :job_title %>
    <%= f.input :description %>
    <%= f.input :goals %>
    <%= f.submit "APPLY", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/registers/show.html.erb
<br />
  <div align="center" class="col-10 offset-1 text-align">
  <h1><%= @register.full_name %>'s Application</h1>
  <p><%= @register.phone_number %></p>
  <p><%= @register.email %></p>
  <p><%= @register.city %></>
</div>

<div class="booyah-box col-10 offset-1">
  <h4>When can you start?</h4><hr>
  <p><%= @register.month %></p>
  <h4>High school?</h4><hr>
  <P><%= @register.highschool %></p>
  <h4>College</h4><hr>
  <p><%= @register.college %></p>
  <h4>Years Completed?</h4><hr>
  <p><%= @register.years %></p>
  <h4>What is your Major?</h4><hr>
  <p><%= @register.major %></p>
  <h4>Most Recent job company name if any</h4><hr>
  <p><%= @register.company_name %></p>
  <h4>Your last job title if any</h4><hr>
  <p><%= @register.job_title %></p>
  <h4>Description of duties, skills used/learned and achievements</h4><hr>
  <p><%= @register.description %></p>
  <h4>What do you wish to get out of this internship experience?</h4><hr>
  <p><%= @register.goals %></p>
</div>

app/views/saves/_button.html.erb
<% if current_user.saved_job?(job) %>
  <%= link_to "Undo", undo_path(job_id: job.id), remote: true, method: :delete, id:"undo"  %>
  <% else %>
  <%= link_to "Save job", save_path(job_id: job.id), remote: true, method: :post, id:"save"  %>
<% end %>

app/views/saves/save.js.erb
$('div#<%= dom_id(@job) %>').html('<%= j render partial: "button", locals: {job: @job} %>');

app/views/saves/undo.js.erb
$('div#<%= dom_id(@job) %>').html('<%= j render partial: "button", locals: {job: @job} %>');

app/views/static_pages/index.html.erb
<div class="hero">
  <br /><br /><br />
  <div class="frosty col-10 offset-1 text-center">
    <br />
    <h1>Get real world experience!</h1>
    <br />
    <div id="index_search" class="form-inline my-2 my-lg-0 col-8 offset-2">
      <%= form_tag(jobs_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], class:"form-control mr-sm-2", placeholder: "What are you looking for?" %>
      <%= submit_tag "Find Internships" , class:"btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </div>
    <!-- <%= link_to 'Find an Internship!', jobs_path, class: 'btn btn-success' %> -->
    <br /><br />
  </div>
</div>
<br />
<div class="row feature text-center">
  <div class="col-12 col-sm">
    <h3>Step 1</h3>
    <br />
    <p>Sign up for an account!</p>
  </div>

  <div class="col-12 col-sm">
    <h3>Step 2</h3>
    <br />
    <p>Search for internships</p>
  </div>

  <div class="col-12 col-sm">
    <h3>Step 3</h3>
    <br />
    <p>Apply!</p>
  </div>
</div>

<div class="hero1">
  <br /><br /><br />
  <div class="frosty col-10 offset-1 text-center">
    <br />
    <h1>How can we help you?</h1>
    <br />
  </div>
</div>
<br />
<div class="row feature text-center">
  <div class="col-12 col-sm">
    <h3>Search millions of internships</h3>
    <br />
    <p>We've got a couple million internships for you to search through and find the right one.</p>
  </div>

  <div class="col-12 col-sm">
    <h3>Find the perfect internship</h3>
    <br />
    <p>The best way to apply what you've learned in school is to use it in the real world.</p>
  </div>

  <div class="col-12 col-sm">
    <h3>Stand out</h3>
    <br />
    <p>An internship experience gives you the hands on experience to help you stand out from the crowd.</p>
  </div>
</div>

app/views/users/show.html.erb
<div class="booyah-box col-10 offset-1">
  <div class="row">
    <div class="col-4">
      <%= image_tag 'user.png' %>
    </div>

    <div class="col-8">
      <h1><%= @user.email %></h1>
      <h3>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
      <h4><%= @user.registers.count %> total jobs you applied for</h4>
    </div>
  </div>
  <div class="clear"></div>
</div>
<!-- Applicants table -->
<br />
<h1 class="text-center">My Applications</h1>
<div class="booyah-box col-10 offset-1">
<table class="table table-hover">
    <thead>

      <tr>
        <th>Job Post</th>
        <th>Name</th>
        <th>Phone Number</th>
        <th>Email</th>
        <th>Action<th>
      </tr>
    </thead>

    <tbody>
      <% @user.registers.each do |register| %>
        <% if register.job.present? %>
          <tr>
            <td><%= link_to register.job.name, job_path(register.job) %></td>
            <td> <%= link_to register.full_name, job_register_path(@user.jobs, register) %></td>
            <td><%= register.phone_number %></td>
            <td><%= register.email %></td>
            <td><%= link_to 'Destroy', job_register_path(register.job, register),
            method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger btn-xs' %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>
<div class="clear"></div>

<% @user.jobs.each do |job| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%=link_to job.title, job_path(job) %></h1>
    <h4><%= job.name %></h4>
    <i><%= job.city %>, <%= job.state %></i><br /><br />
    <p><%= job.description %></p><br />
  </div>
<% end %>
<h3>My saved jobs </h3>
<% @user.my_saved_jobs.each do |job| %>
<div class="booyah-box col-10 offset-1">
  <h1><%=link_to job.title, job_path(job) %></h1>
  <h4><%= job.name %></h4>
  <i><%= job.city %>, <%= job.state %></i><br /><br />
  <p><%= job.description %></p><br />
</div>
<% end %>